version: "3.8"

services:
  nginx:
    image: nginx
    container_name: nginx-container
    expose:
      - 80/tcp
    ports:
      - 80:80
    restart: always
    volumes:
      - ./temp/configs/nginx:/etc/nginx/conf.d:ro
      - ./src:/var/www/gallery:ro
    depends_on:
      - php
      - mysql
      - phpmyadmin
    networks:
      - gallery-network

  php:
    build:
      context: ./dockerfiles/php
      dockerfile: dockerfile
    container_name: php-container
    restart: always
    volumes:
      - ./src:/var/www/gallery
    networks:
      - gallery-network

  composer:
    build:
      context: ./dockerfiles/composer
      dockerfile: dockerfile
    container_name: composer-container
    volumes:
      - ./src:/var/composer/src
    networks:
      - gallery-network

  mysql:
    image: mysql
    container_name: mysql-container
    expose:
      - 3306/tcp
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./databases/mysql:/var/lib/mysql
    env_file:
      - mysql.env
    networks:
      - gallery-network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-container
    expose:
      - 80/tcp
    ports:
      - 8080:80
    restart: always
    env_file:
      - phpmyadmin.env
    networks:
      - gallery-network

networks:
  gallery-network:
    name: gallery-network
    driver: bridge
